### ISSUE TITLE
Simple Example App

### ISSUE THREAD

**Issue by cliftonlabrum** [HandyGram/tdlib#1]
Do you have a simple example app you can share that shows your implementation of tdlib? Specifically something that demonstrates:

1. Initialization of TDLib
2. Setup of TDLib event listener on a background isolate
3. Basic authentication

The Readme of this repo jumps right into some details but it's not clear even how to import this library and start at the beginning.

Thanks!

**Comment by tdrkDev** [comment]
Hello, I know that I'm late. You may find example usage in the `main` branch of HandyGram: https://github.com/HandyGram/HandyGram/tree/main/lib/src/common/tdlib

Everything for managing TDLib clients may be found under `client/` directory, for running management classes - under `runner/`.

"Data repository" layer according to BLoC architecture is located in `providers/` and `services/` (providers are providing data to the Dart side, services are providing data to the TDLib side). There is also useful Cubit for UI in `lib/src/common/cubits/current_account.dart`.

You may also find useful extensions under `extensions/` directory.

There is also useful mixin for preventing boilerplate in TDLib invoke wrappers - `misc/updaters_wrappers.dart` (ik, class name is a bit confusing).

I'll add some wrappers from HandyGram into this library later, it was a mistake to not put them here.
